//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApI_Application.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Customer
    {
        public int customer_id { get; set; }
        public string customer_name { get; set; }
        public Nullable<int> phone_no { get; set; }
        public string password { get; set; }
        public Nullable<System.DateTime> dob { get; set; }
        public Nullable<decimal> account_balance { get; set; }
    }
}
