//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApI_Application.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vendor
    {
        public int vendor_id { get; set; }
        public string vendor_name { get; set; }
        public Nullable<int> vendor_verification_card_id { get; set; }
        public Nullable<int> phone_no { get; set; }
        public string vendor_password { get; set; }
    }
}
